modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
[[mods]]
modId="keeptheresourcepack"
version="${file.jarVersion}"
displayName="KeepTheResourcePack"
authors="focamacho"
description='''
Keep the Resource Pack loaded even after leaving the server.
'''
